export type ComponentKind = "client" | "server" | "hybrid";

export interface SystemComponent {
  id: string;
  name: string;
  kind: ComponentKind;
  technology: string;
  category: string;
  role: string;
  stack: string;
  endpoint: string;
  port?: string;
  isNew?: boolean;
}

export const SYSTEM_COMPONENTS: SystemComponent[] = [
  {
    id: "nextjs",
    name: "Next.js Frontend",
    kind: "client",
    technology: "Next.js 16",
    category: "Browser UI",
    role: "UI, routing, live interview room",
    stack: "Next.js 16 · React 19 · TypeScript",
    endpoint: typeof window !== "undefined" ? window.location.origin : "http://localhost:3000",
    port: "3000",
  },
  {
    id: "laravel",
    name: "Laravel API",
    kind: "server",
    technology: "Laravel 13 / PHP",
    category: "REST API",
    role: "REST API, auth, queues, persistence",
    stack: "Laravel 13 · Sanctum · PHP",
    endpoint: process.env.NEXT_PUBLIC_API_URL?.replace("/api/v1", "") || "http://localhost:8000",
    port: "8000",
  },
  {
    id: "ai-service",
    name: "Python AI Service",
    kind: "server",
    technology: "FastAPI",
    category: "AI Gateway",
    role: "Questions, scoring, Whisper STT, reports, vision behavior analysis & coaching feedback",
    stack: "FastAPI · Ollama · Whisper · MediaPipe · OpenCV · transformers",
    endpoint: "http://127.0.0.1:8001",
    port: "8001",
  },
  {
    id: "reverb",
    name: "Laravel Reverb",
    kind: "server",
    technology: "Reverb / WebSocket",
    category: "Realtime",
    role: "Real-time interview events",
    stack: "WebSocket · Pusher protocol",
    endpoint: `${process.env.NEXT_PUBLIC_REVERB_SCHEME || "http"}://${process.env.NEXT_PUBLIC_REVERB_HOST || "localhost"}:${process.env.NEXT_PUBLIC_REVERB_PORT || "8080"}`,
    port: process.env.NEXT_PUBLIC_REVERB_PORT || "8080",
  },
  {
    id: "queue",
    name: "Queue Worker",
    kind: "server",
    technology: "Laravel Queue",
    category: "Background jobs",
    role: "Evaluate answers, generate questions, analyze behavior, record mastery, send emails",
    stack: "Laravel Queue · Redis/Database",
    endpoint: "Background process",
  },
  {
    id: "ollama",
    name: "Ollama LLM",
    kind: "server",
    technology: "Ollama (Llama 3)",
    category: "AI inference",
    role: "AI question & evaluation generation",
    stack: "Llama 3 · local inference",
    endpoint: "http://127.0.0.1:11434",
    port: "11434",
  },
  {
    id: "whisper",
    name: "Whisper STT",
    kind: "server",
    technology: "Whisper small",
    category: "Speech-to-text",
    role: "Server-side speech-to-text",
    stack: "OpenAI Whisper · ffmpeg",
    endpoint: "ai-service /pipeline/transcribe",
  },
  {
    id: "database",
    name: "Database",
    kind: "server",
    technology: "MySQL / SQLite",
    category: "Persistence",
    role: "Users, interviews, scores, resumes, cross-interview memory (user_question_mastery, user_memory_profiles), behavior metrics (answer_behaviors), full_video_path",
    stack: "MySQL / SQLite",
    endpoint: "Laravel persistence layer",
  },
  {
    id: "media-recorder",
    name: "MediaRecorder",
    kind: "client",
    technology: "Browser MediaRecorder",
    category: "Browser capture",
    role: "Per-answer audio/video capture plus continuous full-session interview recording",
    stack: "Browser Web APIs",
    endpoint: "Client device",
  },
  {
    id: "speech-preview",
    name: "Speech Recognition",
    kind: "client",
    technology: "Web Speech API",
    category: "Browser preview",
    role: "Live caption preview only",
    stack: "Web Speech API",
    endpoint: "Client browser",
  },
  {
    id: "cross-interview-memory",
    name: "Cross-Interview Memory",
    kind: "server",
    technology: "Laravel + MySQL",
    category: "Memory",
    role: "Stores mastered questions and rolling user memory profiles so passed questions and topics are never repeated (mastery threshold 60)",
    stack: "Laravel · MySQL",
    endpoint: "user_question_mastery · user_memory_profiles",
    isNew: true,
  },
  {
    id: "mastery-service",
    name: "Mastery Service",
    kind: "server",
    technology: "Laravel Service",
    category: "Memory",
    role: "Records question mastery after scoring and feeds the memory payload into GenerateQuestionJob",
    stack: "Laravel",
    endpoint: "App\\Services\\Interview\\MasteryService",
    isNew: true,
  },
  {
    id: "vision-pipeline",
    name: "Vision Pipeline",
    kind: "server",
    technology: "FastAPI + MediaPipe + OpenCV + transformers",
    category: "Vision",
    role: "Analyzes recorded answers for facial emotion, gaze, head pose, blink rate, and audio prosody (GPU accelerated)",
    stack: "FastAPI · MediaPipe · OpenCV · transformers · librosa",
    endpoint: "POST /pipeline/vision/analyze",
    isNew: true,
  },
  {
    id: "behavior-job",
    name: "Behavior Analysis Job",
    kind: "server",
    technology: "Laravel Queue",
    category: "Background jobs",
    role: "Calls the vision API per answer and stores confidence, nervousness, and coaching narrative in answer_behaviors",
    stack: "Laravel Queue",
    endpoint: "App\\Jobs\\AnalyzeBehaviorJob",
    isNew: true,
  },
  {
    id: "full-session-recorder",
    name: "Full-Session Recorder",
    kind: "client",
    technology: "Browser MediaRecorder",
    category: "Browser capture",
    role: "Records the entire interview as one continuous video and uploads it when the interview completes",
    stack: "Browser Web APIs",
    endpoint: "POST /interviews/{id}/recording",
    isNew: true,
  },
  {
    id: "media-consent-store",
    name: "Media Consent Store",
    kind: "client",
    technology: "localStorage + Permissions API",
    category: "Browser capture",
    role: "Remembers camera/mic consent (mi_media_consent) and silently re-acquires the stream on return so the permission gate is skipped",
    stack: "localStorage · Permissions API",
    endpoint: "Client browser",
    isNew: true,
  },
];
